// src/app/layout.tsx
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import DashboardWrapper from "./(auth)/dashboardLayout";
import PublicLayout from "./(auth)/publicLayout";
import { dark } from "@clerk/themes"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            <DashboardWrapper>{children}</DashboardWrapper>
          </SignedIn>
          <SignedOut>
            <PublicLayout>{children}</PublicLayout>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
